version: "3.8"

services:

 sqldatabase:
  container_name: sqldatabase
  image: mcr.microsoft.com/mssql/server:2022-latest
  restart: unless-stopped
  ports: 
   - 1433:1433
  volumes:
   - ./sql_volume/data:/var/opt/mssql/data
   - ./sql_volume/log:/var/opt/mssql/log
   - ./sql_volume/secrets:/var/opt/mssql/secrets
  environment:
   - ACCEPT_EULA=Y
   - MSSQL_SA_PASSWORD=${SQL_PASSWORD}

 seq:
  container_name: seq
  image: localhost:8082/datalust/seq:latest
  restart: unless-stopped
  ports: 
   - 5341:80
  environment:
   - ACCEPT_EULA=Y

 user_management:
  container_name: user_management
  image: localhost:8083/user_management:latest
  ports: 
   - 8001:80
  depends_on:
   - "sqldatabase"
   - "seq"
  environment:
   - ConnectionStrings__Local=${SQL_CONNECTION_STRING}
   - EmailConfiguration__From=${EMAIL_CONFIGURATION_FROM}
   - EmailConfiguration__ServerAddress=${EMAIL_CONFIGURATION_SERVER_ADDRESS}
   - EmailConfiguration__UserName=${EMAIL_CONFIGURATION_USERNAME}
   - EmailConfiguration__Password=${EMAIL_CONFIGURATION_PASSWORD}
   - EmailConfiguration__Port=${EMAIL_CONFIGURATION_PORT}
   - Jwt__Audience=http://localhost:8001
   - Jwt__Issuer=http://localhost:8001
   - Jwt__Secret=${JWT_SECRET}
   - GoogleAuthentication__ClientId=${GOOGLE_CLIENT_ID}
   - GoogleAuthentication__SecretId=${GOOGLE_CLIENT_SECRET}
   - Seq__ServerUrl=http://host.docker.internal:5341
   - Seq__ApiKey=${SEQ_API_KEY}
   - Seq__MinimumLevel=Information
   - Seq__LevelOverride__Microsoft=Information
   - System__Url=${SYSTEM_URL}